services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-churn-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: customer-churn-frontend
    ports:
      - "8501:8501"
    environment:
      FASTAPI_URL: http://backend:8000
    depends_on:
      - backend